field_rows=10 # размерность поля (автогенерация)
field_cols=10 # размерность поля (автогенерация)
cell_start=1 # ячейка старт
cell_finish=-1 # ячейка финиш
cell_wall=-2 # ячейка стена
cell_path=-25 # ячейка путь
cell_empty=0 # пустая ячейка
neyman_wave=[[-1, 0], [1, 0], [0, -1], [0, 1]] # волна Неймана
moore_wave=[[-1, 0], [1, 0], [0, -1], [0, 1], [-1, 1], [1, -1], [-1, -1], [1, 1]] # волна Мура
cell_start_color="#ADFF2F" # цвет ячейки старт
cell_finish_color="#ADFF2F" # цвет ячейки финиш
cell_wall_color="#FAEBD7" # цвет ячейки стена
cell_path_color="#FFB6C1" # цвет ячейки путь
cell_empty_color="w" # цвет пустой ячейки